### ISSUE TITLE
Hover rotates image to the right by 90 degrees

### ISSUE THREAD

**Issue by GaryKing** [dadler/thumbnail-zoom#174]
For me, [this image](https://upload.wikimedia.org/wikipedia/commons/f/f7/Zoe_Quinn_-_GDC_2014.jpg) is rotated when I hover over it. Click through to the original image to see that it should not be the case.

Firefox latest, Mac latest.

**Comment by dadler** [comment]
This is a dup of (newer) issue #214; see that issue for more...
