### ISSUE TITLE
Feature request - make it possible to use "Save image as" on the zoomed image.

### ISSUE THREAD

**Issue by 20150131** [dadler/thumbnail-zoom#196]
Example: 

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Zappa_16011977_01_300.jpg/220px-Zappa_16011977_01_300.jpg">

It would be really nice to be able to use "Save image as" for the zoom after mousing over the thumb.

**Comment by dadler** [comment]
This is already supported.  Press "s" while a pop-up is displayed or right click after a pop up is displayed and select the save zoomed image as menu item.
