### ISSUE TITLE
download API change in FF36 breaks 'Save'

### ISSUE THREAD

**Issue by computertechie** [dadler/thumbnail-zoom#198]
Having received to response to my email to @dadler I will copy/paste it here as a Github issue in hopes it receives a response here:

Hi David,
As an avid user of TZP I was quite disconcerted when downloads through TZP would fail (rather, hang forever unfinished) once my installation of FF was promoted to 36 beta (I do use the beta channel).

I started debugging TPZ and encountered the following error:

NS_ERROR_XPC_NOT_ENOUGH_ARGS: Not enough arguments [nsIWebBrowserPersist.saveURI] downloadService.js:144:0 

After looking through docs and editing of the extension locally (adding another null arg fixes the issue), I looked at the FF source for changes and found the following changeset: 

http://hg.mozilla.org/mozilla-central/diff/4a7db36c3c75/embedding/components/webbrowserpersist/nsIWebBrowserPersist.idl

In the process of adding referrer policy support for nsIWebBrowserPersist, compatibility has been broken with FF36. 
The docs for nsIWebBrowserPersist have been updated to list all 8 args now:

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIWebBrowserPersist

The simplest solution is to add a null argument in the place of the new referrer policy, but that will break compatibility with versions < 36 (I’m not quite sure how add-on versioning works in regards to old browser versions and compatible add-on versions).

Alternatively, as the nsIWebBrowserPersist docs recommend, TZP could be switched to use Downloads.createDownload() ( https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Downloads.jsm#createDownload%28%29 ) instead, which should maintain compatibility to at least FF26, if not earlier.

If you’re not already aware of this change, hopefully this has been helpful! TPZ is the most useful extension I have.

PS: TPZ isn’t compatible with FF3.0 as reported on the add-ons site (I was testing my local edits trying to fix the referrer issue): Some component expected by overlay.js doesn’t exist in such an early version.

**Comment by 20150131** [comment]
> Having received to response 

I'm sure that's a typo and you meant "no response".

Is this add-on dead? I made a bunch of posts before yours (~8 days ago) and there are no comments from the mods.

**Comment by computertechie** [comment]
Er yes, that is indeed a typo.

I'm not sure if @dadler is still continuing work on this project; the last beta was released on January 3. I suppose it's quite possible he's been kept busy with other things, but having no reply to anything for a month or more is worrying.

**Comment by dadler** [comment]
Yep, just busy, but not abandoned!

**Comment by dadler** [comment]
This is fixed in 3.3beta3, though as a short-term fix (adding the extra argument).  When I have more time it'd be better to use Downloads.createDownload() instead, but the old approach would still be needed for older than ff 26.

**Comment by computertechie** [comment]
Thanks :)

Looking at the commit, I'd think switching the line in the try{} to the createDownload() method would function just as it does now, falling to the catch if Downloads doesn't exist.

**Comment by dadler** [comment]
Yeah, it may be easy but I'm not sure if I also need to make a task like the page shows.  In any case, I wanted to make the minimal code change fix initially to get something out quickly.
