### ISSUE TITLE
Broken on Facebook profile pictures

### ISSUE THREAD

**Issue by bpsib** [dadler/thumbnail-zoom#213]
It seems Facebook have changed something so it has stopped working for profile pictures. It now doesn't work at all for any profile picture on the hovercards.

**Comment by dadler** [comment]
Hmm... it still works for me.  

What version of Firefox?  
What version of Thumbnail Zoom Plus?
What facebook URL -- eg facebook.com or a non-US URL?  
What language is Facebook set to (if not English)?  
Does it still work for Facebook images other than hovercard profile pics?

**Comment by bpsib** [comment]
It seems like it has fixed itself. It's working fine again. Not sure if it was just a temporary glitch.

**Comment by mleyen** [comment]
As of May 16, it appears to be broken again.
When I press T to open the enlarged image in a new tab, it opens `https://graph.facebook.com/<username>/picture?width=750&height=750`, which shows this message : 
```json
{
   "error": {
      "message": "(#803) Cannot query users by their username (<redacted>)",
      "type": "OAuthException",
      "code": 803
   }
}
```

So I guess Facebook changed their API for some reason. We ned a way to retrieve the user ID instead.

This is only on hovercard profile pics; still working on regular photos.

**Comment by dadler** [comment]
Yep, I noticed that too.  I took a quick try at fixing it, but no joy yet...
