### ISSUE TITLE
Does Not Work On Firefox 40.0a2 (Multi-Process)

### ISSUE THREAD

**Issue by DeathTheKid** [dadler/thumbnail-zoom#216]
I am just testing out my favorite add-ons to see how they work in e10.  Thumbnail-zoom doesn't work at all.

**Comment by dadler** [comment]
It should work in TZP 3.6 -- I believe most sites and features work, but it's using "compatibility shims" and so isn't optimized for maximum speed (which would take a bunch more work).

**Comment by dadler** [comment]
Related issues: #160, #247.  Closing since 4.0 seems to work in E10S (with some limitations as listed in #247).
