### ISSUE TITLE
Facebook hover sometimes wrong

### ISSUE THREAD

**Issue by sp00n** [dadler/thumbnail-zoom#218]
On a couple of Facebook posts, the hover images doesn't show the correct picture. Most of the time it works though, which makes it so irritating.

Example post:
https://www.facebook.com/tyrionfans/photos/a.546670775405649.1073741828.546601852079208/940543642685025/?type=1

When hovering over the "Open photo viewer" arrows on the top right it shows the first image below the post, and not the original image (the same happens when hovering over the image in the news feed).

**Comment by dadler** [comment]
What version of TZP?  I think I fixed this in 3.6beta3.

**Comment by sp00n** [comment]
It was beta2, which was the most recent at that time. Beta3 seems to have fixed this, indeed.
