### ISSUE TITLE
Facebook : some profile pictures don't get maximal zoom

### ISSUE THREAD

**Issue by mleyen** [dadler/thumbnail-zoom#219]
Profile pictures without a public photo page (i.e. the ones who links to https://www.facebook.com/profile/picture/view/?profile_id=<userID> and do not show the comments) do not get maximised to the max when hovered. This happens even in hovercards.

**Comment by dadler** [comment]
Thanks for the bug report.  This problem happens in v3.6beta3.  I expect it to be fixed in v3.6beta4.

**Comment by dadler** [comment]
The fix is in 3.6beta4, now available.  https://addons.mozilla.org/en-US/firefox/addon/thumbnail-zoom-plus/versions/
