### ISSUE TITLE
Sometimes works, sometimes doesn't

### ISSUE THREAD

**Issue by DBGulp** [dadler/thumbnail-zoom#221]
Possibly, in the latest release TZ+ works and sometimes it doesn't. It can work for an image and then it stops working if I hover the image another time. I may have to refresh the page that I just opened if it doesn't function and then it will work as expected. On a page with multiple images it may work for several and then stop working.

In this example http://forums.mozillazine.org/viewtopic.php?f=48&t=2827985&start=2805 post 2818, not numbered, July 27 10:06pm, a long post, there are two image links. http://imgur.com/JqKJgBL and http://imgur.com/ixboNV1 I hovered over the first image nothing happened. I had to click the link and view in a new tab. After returning to original tab I hovered over the second link and it worked. I hovered the first link and now it worked. I returned to the second link and it stopped working.
I reverted back to TZ+ 3.5.1 which functions as expected.

**Comment by dadler** [comment]
Are you  using an old version of Firefox or using Pale Moon?  Version 3.6 has a compatibility problem, which is fixed in 3.7beta1.  https://addons.mozilla.org/en-US/firefox/addon/thumbnail-zoom-plus/versions/

**Comment by DBGulp** [comment]
One machine Windows 7 FFX 32.0.3 One machine Vista FFX 33, I think, not on that one at the moment.
I saw 28 listed as an older version. So, I assumed above that was OK. I can try the 3.7beta1.

**Comment by dadler** [comment]
I don't know exactly which versions are bad; 28 doesn't work with 3.6; 39 does; in-between I don't know.  There's a good chance 3.7beta1 will solve your problem.

**Comment by DBGulp** [comment]
3.7 seems to be working correctly. on Vista FFX33. 3.7 Beta1 seemed OK on 7 FFX 32.0.3. I haven't tested much but no issues yet.
