### ISSUE TITLE
[Request] Add i.reddituploads.com

### ISSUE THREAD

**Issue by mleyen** [dadler/thumbnail-zoom#228]
i.reddituploads.com is Reddit's new domain for images uploaded from the official app.

The links are all images, but they don't have an image extension and have extra parameters in the URL so they won"t be expanded by TZP.

Example URL : https://i.reddituploads.com/27421cd527ac4c5db7ece87806ce1869?fit=max&h=1536&w=1536&s=dd2fae177b7032c87458887bc8c60859

More examples : https://www.reddit.com/domain/i.reddituploads.com

**Comment by dadler** [comment]
reddituploads.com and redd.it are supported in version 4.0beta1. https://addons.mozilla.org/en-US/firefox/addon/thumbnail-zoom-plus/versions/
