### ISSUE TITLE
Not working properly on Firefox 45.0/Linux Mint 17.3 Cinnamon 64-bit

### ISSUE THREAD

**Issue by rianmcc** [dadler/thumbnail-zoom#230]
Whenever I hover over a thumbnail it pops up very briefly and disappears. I then have to hover over it again and then it will stay on the screen. However, I can't use the keyboard shortcuts like 's' for saving or the arrow keys for scrolling through a gallery.

If I disable "Popup takes keyboard focus", the brief flash problem is fixed but I still can't use any keyboard shortcuts.

I have tried disabling all the add-ons and even setting up a temporary Firefox profile to test the addon but neither solved the problem.

Here is the link to the debug log: http://pastebin.com/FZvqcM08. While this was running, I tried scrolling over images and using shortcuts.

**Comment by Ronifae** [comment]
Running Waterfox 46.0.1 with latest version of Thumbnail Zoom (3.8) on Win 7 (64bit). 
Nothing is working anywhere. No flashing of pictures or images. No error messages. There are many people complaining on Thumbnail's Facebook page with no response from the page admin.
How far back do I have to take Waterfox to get this addon to work again?
