### ISSUE TITLE
Add reddituploads.com

### ISSUE THREAD

**Issue by GaryKing** [dadler/thumbnail-zoom#236]
Reddit has started hosting their own images now. [Sample post](https://www.reddit.com/r/pics/comments/4la8zn/my_breakfast_view_in_a_cafe_on_pulteney_bridge/) which links to [sample image](https://i.reddituploads.com/1e770a28f5a046c4bab1e1e052db7e29?fit=max&h=1536&w=1536&s=40ad0d78b21e8b529ff2db21f966f013).

**Comment by dadler** [comment]
Merging with #228.

**Comment by dadler** [comment]
reddituploads.com and redd.it are supported in version 4.0beta1.  https://addons.mozilla.org/en-US/firefox/addon/thumbnail-zoom-plus/versions/
